
import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Nessun Dorma',
    category: 'KLASIKINIS MIŠINYS',
    price: 24,
    notes: ['lazdynas', 'kakava', 'gėlės', 'citrusai'],
    roast: 'VIDUTINĖS SKRUDINIMAS',
    origin: 'Triestas, Italija',
    process: 'Tradicinis skrudinimas ant malkų',
    description: 'Refinuotas mišinys, suteikiantis pilnatvišką skonių visumą. Lazdyno riešuto skonis tampa pagrindu, iš kurio kakavos natos, gėlių aromatai ir citrusų užuomina susijungia harmonijoje, sukuriančioje nuolat kintančią saldžių, kartių ir rūgščių balansą, apgaubiančią gomurį įvairių skonių gausa.',
    rating: 4.8,
    reviewCount: 156,
    image: 'https://i.postimg.cc/3rV1H6sG/Nessun_Dorma.png',
    accentColor: 'bg-terracotta',
    limited: false,
    profile: { intensity: 8, body: 8, acidity: 6, crema: 9 }
  },
  {
    id: '2',
    name: 'Risvegli',
    category: 'INTENSYVUS MIŠINYS',
    price: 26,
    notes: ['kakava', 'lazdynas', 'jazminas'],
    roast: 'VIDUTINIŠKAI TAMSUS SKRUDINIMAS',
    origin: 'Triestas, Italija',
    process: 'Tradicinis skrudinimas ant malkų',
    description: 'Ryžtingas mišinys, kuriame intensyvios kakavos natos susimaišo su lazdyno riešutų skoniu ir jazmino aromatu, sukurdamos unikalią sąjungą tarp ne pernelyg stipraus, bet malonaus kartumo ir saldumo. Mišinys tiems, kurie mėgsta ilgai išliekantį kavos skonį gomuryje – jo aromatas stiprus, bet neįkyrus.',
    rating: 4.9,
    reviewCount: 203,
    image: 'https://i.postimg.cc/FFWy9c3d/Risvegli.png',
    accentColor: 'bg-heritageBlack',
    limited: false,
    profile: { intensity: 9, body: 9, acidity: 5, crema: 9 }
  },
  {
    id: '3',
    name: 'Buonissimo',
    category: 'STIPRUS MIŠINYS',
    price: 28,
    notes: ['kakava', 'gėlės', 'vanilė'],
    roast: 'TAMSUS SKRUDINIMAS',
    origin: 'Triestas, Italija',
    process: 'Tradicinis skrudinimas ant malkų',
    description: 'Šis mišinys pasižymi intensyviu ir maloniu kūnu, kuriame kakavos skonis, maloniai kartus, vyrauja ant pagrindo, kurio charakteristiką sudaro gėlių ir vanilės saldumas. Išliekanti kremė kartu su intensyviu aromatu daro jį idealiu tiems, kurie mėgsta gerą kapučino ar makijato be tradicinio espresso. Stiprus ir ilgai išliekantis skonis.',
    rating: 5.0,
    reviewCount: 267,
    image: 'https://i.postimg.cc/v8khdjJL/Buonissimo.png',
    accentColor: 'bg-mustard',
    limited: false,
    profile: { intensity: 10, body: 10, acidity: 4, crema: 10 }
  },
  {
    id: '4',
    name: 'Organic BIO',
    category: 'ORGANIKA',
    price: 30,
    notes: ['lazdynas', 'šokoladas', 'struktūrinė rūgštis'],
    roast: 'VIDUTINĖS SKRUDINIMAS',
    origin: 'Organiniai ūkiai',
    process: 'Organinis sertifikavimo procesas',
    description: 'Kava, gaunama iš kruopščios atrankos, kuri, remdamasi išskirtinai ekologiniais pasėliais, nori pasiūlyti geriausią organoleptinių skonių, kurių spektras gali svyruoti nuo lazdyno iki šokolado iki struktūrinės rūgšties, būdingos prestižinėms kavoms, atžvilgiu. Išliekanti, bet neįkyri kava, atnaujinanti gomurį paliekanti malonų pojūtį.',
    rating: 4.6,
    reviewCount: 124,
    image: 'https://i.postimg.cc/KcwfyV67/Organic_BIO.png',
    accentColor: 'bg-sage',
    limited: false,
    profile: { intensity: 7, body: 6, acidity: 7, crema: 6 }
  },
  {
    id: '5',
    name: 'Nabucco',
    category: 'ARABIKOS MIŠINYS',
    price: 32,
    notes: ['kakava', 'vanilė'],
    roast: 'VIDUTINIŠKAI TAMSUS SKRUDINIMAS',
    origin: '100% Arabikos atranka',
    process: 'Tradicinis skrudinimas ant malkų',
    description: '100% Arabikos mišinys su išreikštomis kakavos natomis, iškylančiomis iš pagrindo, kurio ryškiausia charakteristika yra vanilės saldumas. Idealus tiems, kurie ieško intensyvumo kavoje, neprivedami savęs nuo aromatinio mišinio malonumo.',
    rating: 4.7,
    reviewCount: 189,
    image: 'https://i.postimg.cc/qBSwdYPn/Nabucco.png',
    accentColor: 'bg-terracotta',
    limited: false,
    profile: { intensity: 10, body: 9, acidity: 3, crema: 9 }
  },
  {
    id: '6',
    name: 'Decaffeinate',
    category: 'BEKOFAINĖ',
    price: 27,
    notes: ['šokoladas', 'vanilė', 'gėlės'],
    roast: 'VIDUTINĖS SKRUDINIMAS',
    origin: 'Triestas, Italija',
    process: 'Dekofeinizacijos procesas',
    description: 'Mišinys, kuris nustebins jus aromatų įvairove, tokia kaip šokoladas, vanilė ir gėlės, kurios susiliejusios sukuria bendrą balansą. Kava, atlaisvinta nuo kofeino, bet ne nuo malonumo išlaikyti apvalų ir aksominį skonį gomuryje.',
    rating: 4.4,
    reviewCount: 98,
    image: 'https://i.postimg.cc/bYWgjM76/Decaffeinate.png',
    accentColor: 'bg-mustard',
    limited: false,
    profile: { intensity: 7, body: 7, acidity: 5, crema: 8 }
  },
  {
    id: '7',
    name: 'Figaro',
    category: 'STIPRUS CHARAKTERIS',
    price: 29,
    notes: ['kakava', 'prieskoniai'],
    roast: 'TAMSUS SKRUDINIMAS',
    origin: 'Triestas, Italija',
    process: 'Tradicinis skrudinimas ant malkų',
    description: 'Kava su stipriu ir drąsiu charakteriu, kurioje nuostabus kakavos aromatas, pagyvintas prieskonių natomis, užvaldo ir pažadina jausmus stiprios emocijos galia.',
    rating: 4.8,
    reviewCount: 145,
    image: 'https://i.postimg.cc/hPmr4snV/Figaro.png',
    accentColor: 'bg-heritageBlack',
    limited: false,
    profile: { intensity: 10, body: 10, acidity: 2, crema: 9 }
  },
  {
    id: '8',
    name: 'Rigoletto',
    category: 'HARMONINGAS MIŠINYS',
    price: 25,
    notes: ['kakava', 'citrusai', 'gėlės'],
    roast: 'VIDUTINĖS SKRUDINIMAS',
    origin: 'Triestas, Italija',
    process: 'Tradicinis skrudinimas ant malkų',
    description: 'Kava su apvaliu ir apgaubiančiu skoniu, kuriame kūnas ir intensyvios kakavos natos susilieja glėbyje su citrusų natų švelnumu ir gėlių aromatų saldumu, sukurdamos harmoningą aromatų mišinį.',
    rating: 4.6,
    reviewCount: 167,
    image: 'https://i.postimg.cc/wTNVx2zc/Rigoletto.png',
    accentColor: 'bg-sage',
    limited: false,
    profile: { intensity: 8, body: 9, acidity: 6, crema: 9 }
  }
];
