
import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Nessun Dorma',
    category: 'SIGNATURE BLEND',
    price: 24,
    notes: ['hazelnut', 'cocoa', 'floral', 'citrus'],
    roast: 'MEDIUM ROAST',
    origin: 'Trieste, Italy',
    process: 'Traditional wood-fired roasting',
    description: 'A captivating blend that opens with soft, warm tones, gradually revealing a crescendo of cocoa, hazelnut, florals, and a gentle citrus lift. Intense and enveloping, with a persistent, elegant finish.',
    rating: 4.8,
    reviewCount: 156,
    image: 'https://i.postimg.cc/3rV1H6sG/Nessun_Dorma.png',
    accentColor: 'bg-terracotta',
    limited: false,
    profile: { intensity: 8, body: 8, acidity: 6, crema: 9 }
  },
  {
    id: '2',
    name: 'Risvegli',
    category: 'INTENSE BLEND',
    price: 26,
    notes: ['cocoa', 'hazelnut', 'jasmine'],
    roast: 'MEDIUM-DARK ROAST',
    origin: 'Trieste, Italy',
    process: 'Traditional wood-fired roasting',
    description: 'A bold blend where deep cocoa tones meet hazelnut sweetness and a floral jasmine accent. Structured, persistent, and intensely aromatic—built for those who love a long finish on the palate.',
    rating: 4.9,
    reviewCount: 203,
    image: 'https://i.postimg.cc/FFWy9c3d/Risvegli.png',
    accentColor: 'bg-heritageBlack',
    limited: false,
    profile: { intensity: 9, body: 9, acidity: 5, crema: 9 }
  },
  {
    id: '3',
    name: 'Buonissimo',
    category: 'BOLD BLEND',
    price: 28,
    notes: ['cocoa', 'floral', 'vanilla'],
    roast: 'DARK ROAST',
    origin: 'Trieste, Italy',
    process: 'Traditional wood-fired roasting',
    description: 'Dark and velvety with a persistent crema. Cocoa leads the profile, lifted by soft floral sweetness and a hint of vanilla. Excellent for espresso, cappuccino, and milk drinks—rich, round, and long-lasting.',
    rating: 5.0,
    reviewCount: 267,
    image: 'https://i.postimg.cc/v8khdjJL/Buonissimo.png',
    accentColor: 'bg-mustard',
    limited: false,
    profile: { intensity: 10, body: 10, acidity: 4, crema: 10 }
  },
  {
    id: '4',
    name: 'Organic BIO',
    category: 'ORGANIC',
    price: 30,
    notes: ['hazelnut', 'chocolate', 'structured acidity'],
    roast: 'MEDIUM ROAST',
    origin: 'Certified organic farms',
    process: 'Organic-certified sourcing',
    description: 'Authentic and natural, sourced from sustainable agriculture. Notes of hazelnut and cocoa unfold in a soft, refined texture, supported by a lively, structured acidity that keeps the cup delicate, stimulating, and clean.',
    rating: 4.6,
    reviewCount: 124,
    image: 'https://i.postimg.cc/KcwfyV67/Organic_BIO.png',
    accentColor: 'bg-sage',
    limited: false,
    profile: { intensity: 7, body: 6, acidity: 7, crema: 6 }
  },
  {
    id: '5',
    name: 'Nabucco',
    category: '100% ARABICA',
    price: 32,
    notes: ['cocoa', 'vanilla'],
    roast: 'MEDIUM-DARK ROAST',
    origin: 'Selection of 100% Arabica',
    process: 'Traditional wood-fired roasting',
    description: 'A solemn and harmonious 100% Arabica. Rich cocoa notes blend gracefully with vanilla in a majestic embrace—balanced, noble, and persistent without sacrificing aromatic elegance.',
    rating: 4.7,
    reviewCount: 189,
    image: 'https://i.postimg.cc/qBSwdYPn/Nabucco.png',
    accentColor: 'bg-terracotta',
    limited: false,
    profile: { intensity: 10, body: 9, acidity: 3, crema: 9 }
  },
  {
    id: '6',
    name: 'Decaffeinate',
    category: 'DECAFFEINATED',
    price: 27,
    notes: ['chocolate', 'vanilla', 'floral'],
    roast: 'MEDIUM ROAST',
    origin: 'Trieste, Italy',
    process: 'Decaffeination process',
    description: 'A decaffeinated blend with a surprisingly rich aromatic palette—chocolate, vanilla, and floral softness in a rounded, velvety cup. Caffeine-free, yet never deprived of pleasure or balance.',
    rating: 4.4,
    reviewCount: 98,
    image: 'https://i.postimg.cc/bYWgjM76/Decaffeinate.png',
    accentColor: 'bg-mustard',
    limited: false,
    profile: { intensity: 7, body: 7, acidity: 5, crema: 8 }
  },
  {
    id: '7',
    name: 'Figaro',
    category: 'CHARISMATIC BLEND',
    price: 29,
    notes: ['cocoa', 'spices'],
    roast: 'DARK ROAST',
    origin: 'Trieste, Italy',
    process: 'Traditional wood-fired roasting',
    description: 'Lively and charismatic, this coffee surprises with a decisive rhythm. Notes of cocoa and spices intertwine in a brilliant play of aromas that awaken the senses with energy and personality.',
    rating: 4.8,
    reviewCount: 145,
    image: 'https://i.postimg.cc/hPmr4snV/Figaro.png',
    accentColor: 'bg-heritageBlack',
    limited: false,
    profile: { intensity: 10, body: 10, acidity: 2, crema: 9 }
  },
  {
    id: '8',
    name: 'Rigoletto',
    category: 'HARMONIOUS BLEND',
    price: 25,
    notes: ['cocoa', 'citrus', 'floral'],
    roast: 'MEDIUM ROAST',
    origin: 'Trieste, Italy',
    process: 'Traditional wood-fired roasting',
    description: 'A blend with a deep, dramatic character, where the sweetness of flowers and citrus converge. The flavor unfolds like a passionate melody, leaving an elegant, intense persistence.',
    rating: 4.6,
    reviewCount: 167,
    image: 'https://i.postimg.cc/wTNVx2zc/Rigoletto.png',
    accentColor: 'bg-sage',
    limited: false,
    profile: { intensity: 8, body: 9, acidity: 6, crema: 9 }
  }
];
